### ISSUE TITLE
To Improve!!

### ISSUE THREAD

**Issue by Gill1000** [tarcisio-marinho/cryptomining#1]
I m using xmrig as a malware that is persistence and stop mining when task manager opens or anyother app is open like taskmanager!!
It has no dependicies needed..its a standalone malware.
happygill1000@gmail.com or whatsapp
+91 7888905540
update>>oops i forget to read it is for linux 
sorry

**Comment by tarcisio-marinho** [comment]
Thanks for that mate.
I'm developing from scratch this cryptominer, for linux systems.
Someday on the future I'll try to port it to windows. 
I think I will use CGminer or CCminer to mine the bitcoins on some mining pool.

At the moment I'm trying to develop the multithread server from scratch and client (miner).
Next steps will be creating threads and new process to check when task manager(htop, top, etc...) is running, and some persistence techniques.
